spring:
# 这个匹配url/static/** 请求 都到下面的resources : static-locations里找。
  mvc :
    static-path-pattern : /static/**
  #跟据配置前后顺序找资源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/light?characterEncoding=utf-8&useSSL=false
  thymeleaf:
    cache: true #开启thymeleaf缓存
    prefix: classpath:/templates/
  web:
    resources:
      static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台日志配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  servlet:
    session:
      timeout: 120
